// فيه كل دول العالم
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

class AppCountries {
  static List<Locale> supportedLocales = [
    Locale("أفغانستان"),
    Locale("ألبانيا"),
    Locale("الجزائر"),
    Locale("ساموا الأمريكية"),
    Locale("أندورا"),
    Locale("أنجولا"),
    Locale("أنجويلا"),
    Locale("القارة القطبية الجنوبية"),
    Locale("أنتيغوا وبربودا"),
    Locale("الأرجنتين"),
    Locale("أرمينيا"),
    Locale("أروبا"),
    Locale("أستراليا"),
    Locale("النمسا"),
    Locale("أذربيجان"),
    Locale("جزر البهاما"),
    Locale("البحرين"),
    Locale("بنغلاديش"),
    Locale("بربادوس"),
    Locale("روسيا البيضاء"),
    Locale("بلجيكا"),
    Locale("بليز"),
    Locale("بنين"),
    Locale("برمودا"),
    Locale("بوتان"),
    Locale("بوليفيا"),
    Locale("البوسنة والهرسك"),
    Locale("بوتسوانا"),
    Locale("جزيرة بوفيه"),
    Locale("البرازيل"),
    Locale("إقليم المحيط الهندي البريطاني"),
    Locale("جزر فيرجن البريطانية"),
    Locale("بروناي"),
    Locale("بلغاريا"),
    Locale("بوركينا فاسو"),
    Locale("بوروندي"),
    Locale("كمبوديا"),
    Locale("الكاميرون"),
    Locale("كندا"),
    Locale("الرأس الأخضر"),
    Locale("جزر كايمان"),
    Locale("جمهورية أفريقيا الوسطى"),
    Locale("تشاد"),
    Locale("تشيلي"),
    Locale("الصين"),
    Locale("جزيرة الكريسماس"),
    Locale("جزر كوكوس كيلينغ"),
    Locale("كولومبيا"),
    Locale("جزر القمر"),
    Locale("الكونغو - برازافيل"),
    Locale("الكونغو - كينشاسا"),
    Locale("جزر كوك"),
    Locale("كوستاريكا"),
    Locale("ساحل العاج"),
    Locale("كرواتيا"),
    Locale("كوبا"),
    Locale("كوراساو"),
    Locale("قبرص"),
    Locale("التشيك"),
    Locale("الدنمارك"),
    Locale("جيبوتي"),
    Locale("دومينيكا"),
    Locale("جمهورية الدومينيكان"),
    Locale("الإكوادور"),
    Locale("مصر"),
    Locale("السلفادور"),
    Locale("غينيا الاستوائية"),
    Locale("إريتريا"),
    Locale("إستونيا"),
    Locale("إسواتيني"),
    Locale("إثيوبيا"),
    Locale("جزر فوكلاند"),
    Locale("جزر فارو"),
    Locale("فيجي"),
    Locale("فنلندا"),
    Locale("فرنسا"),
    Locale("غويانا الفرنسية"),
    Locale("بولينيزيا الفرنسية"),
    Locale("الأقاليم الجنوبية الفرنسية"),
    Locale("الغابون"),
    Locale("غامبيا"),
    Locale("جورجيا"),
    Locale("ألمانيا"),
    Locale("غانا"),
    Locale("جبل طارق"),
    Locale("اليونان"),
    Locale("جرينلاند"),
    Locale("غرينادا"),
    Locale("جوادلوب"),
    Locale("غوام"),
    Locale("غواتيمالا"),
    Locale("غيرنزي"),
    Locale("غينيا"),
    Locale("غينيا بيساو"),
    Locale("غيانا"),
    Locale("هايتي"),
    Locale("جزر هيرد وماكدونالد"),
    Locale("هندوراس"),
    Locale("هونغ كونغ"),
    Locale("المجر"),
    Locale("آيسلندا"),
    Locale("الهند"),
    Locale("إندونيسيا"),
    Locale("إيران"),
    Locale("العراق"),
    Locale("أيرلندا"),
    Locale("جزيرة مان"),
    Locale("إسرائيل"),
    Locale("إيطاليا"),
    Locale("جامايكا"),
    Locale("اليابان"),
    Locale("جيرزي"),
    Locale("الأردن"),
    Locale("كازاخستان"),
    Locale("كينيا"),
    Locale("كيريباتي"),
    Locale("كوسوفو"),
    Locale("الكويت"),
    Locale("قيرغيزستان"),
    Locale("لاوس"),
    Locale("لاتفيا"),
    Locale("لبنان"),
    Locale("ليسوتو"),
    Locale("ليبيريا"),
    Locale("ليبيا"),
    Locale("ليختنشتاين"),
    Locale("ليتوانيا"),
    Locale("لوكسمبورغ"),
    Locale("ماكاو"),
    Locale("مدغشقر"),
    Locale("مالاوي"),
    Locale("ماليزيا"),
    Locale("المالديف"),
    Locale("مالي"),
    Locale("مالطا"),
    Locale("جزر مارشال"),
    Locale("مارتينيك"),
    Locale("موريتانيا"),
    Locale("موريشيوس"),
    Locale("مايوت"),
    Locale("المكسيك"),
    Locale("ميكرونيزيا"),
    Locale("مولدوفا"),
    Locale("موناكو"),
    Locale("منغوليا"),
    Locale("الجبل الأسود"),
    Locale("مونتسيرات"),
    Locale("المغرب"),
    Locale("موزمبيق"),
    Locale("ميانمار"),
    Locale("ناميبيا"),
    Locale("ناورو"),
    Locale("نيبال"),
    Locale("هولندا"),
    Locale("كاليدونيا الجديدة"),
    Locale("نيوزيلندا"),
    Locale("نيكاراغوا"),
    Locale("النيجر"),
    Locale("نيجيريا"),
    Locale("نيوي"),
    Locale("جزيرة نورفولك"),
    Locale("كوريا الشمالية"),
    Locale("مقدونيا الشمالية"),
    Locale("جزر ماريانا الشمالية"),
    Locale("النرويج"),
    Locale("عمان"),
    Locale("باكستان"),
    Locale("بالاو"),
    Locale("الأراضي الفلسطينية"),
    Locale("بنما"),
    Locale("بابوا غينيا الجديدة"),
    Locale("باراغواي"),
    Locale("بيرو"),
    Locale("الفلبين"),
    Locale("جزر بيتكيرن"),
    Locale("بولندا"),
    Locale("البرتغال"),
    Locale("بورتو ريكو"),
    Locale("قطر"),
    Locale("ريونيون"),
    Locale("رومانيا"),
    Locale("روسيا"),
    Locale("رواندا"),
    Locale("ساموا"),
    Locale("سان مارينو"),
    Locale("ساو تومي وبرينسيبي"),
    Locale("السعودية"),
    Locale("السنغال"),
    Locale("صربيا"),
    Locale("سيشل"),
    Locale("سيراليون"),
    Locale("سنغافورة"),
    Locale("سنت مارتن"),
    Locale("سلوفاكيا"),
    Locale("سلوفينيا"),
    Locale("جزر سليمان"),
    Locale("الصومال"),
    Locale("جنوب أفريقيا"),
    Locale("جزر جورجيا الجنوبية وساندويتش الجنوبية"),
    Locale("كوريا الجنوبية"),
    Locale("جنوب السودان"),
    Locale("إسبانيا"),
    Locale("سريلانكا"),
    Locale("سانت بارتيلمي"),
    Locale("سانت هيلينا"),
    Locale("سانت كيتس ونيفيس"),
    Locale("سانت لوسيا"),
    Locale("سانت مارتن"),
    Locale("سانت بيير وميكلون"),
    Locale("سانت فينسنت وجزر غرينادين"),
    Locale("السودان"),
    Locale("سورينام"),
    Locale("),سفالبارد ويان ماين"),
    Locale("السويد"),
    Locale("سويسرا"),
    Locale("سوريا"),
    Locale("تايوان"),
    Locale("طاجيكستان"),
    Locale("تنزانيا"),
    Locale("تايلاند"),
    Locale("ة"),
    Locale("توغو"),
    Locale("توكيلاو"),
    Locale("تونغا"),
    Locale("ترينيداد وتوباغو"),
    Locale("تونس"),
    Locale("تركيا"),
    Locale("تركمانستان"),
    Locale("),جزر تركس وكايكوس"),
    Locale("توفالو"),
    Locale("أوغندا"),
    Locale("أوكرانيا"),
    Locale("الإمارات"),
    Locale("المملكة المتحدة"),
    Locale("الولايات المتحدة"),
    Locale("الأوروغواي"),
    Locale("أوزبكستان"),
    Locale("فانواتو"),
    Locale("الفاتيكان"),
    Locale("فنزويلا"),
    Locale("فيتنام"),
    Locale("),واليس وفوتونا"),
    Locale("اليمن"),
    Locale("زامبيا"),
    Locale("زيمبابوي"),
  ];

// المندوبين للغات المدعومة
  static const localizationsDelegates = [
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];
}
