name: awallimna
description: "منصة القصص والروايات متعددة اللغات المدعومة بالذكاء الاصطناعي."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # مكتبات أساسية
  flutter_localized_locales: ^2.0.5
  provider: ^6.0.5
  flip_card: ^0.7.0

  # المكتبات الإضافية
  go_router: ^16.2.4
  dart_jsonwebtoken: ^3.2.0
  shared_preferences: ^2.5.3

  # المكتبات الخاصة
  cupertino_icons: ^1.0.8
  flutter_pdfview: ^1.4.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  characters: 1.4.1
  material_color_utilities: 0.13.0
  meta: 1.17.0
  test_api: 0.7.7
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
